### PR TITLE
Add dot notation and __exists support

### LINKED ISSUE #139: Select query for nested object
Hello,

I have row in collection like
{ 
    "_id" : ObjectId("57a9dd468218dde42cd3453a"), 
    "Date" : ISODate("2016-08-09T13:40:22.887+0000"), 
    "stock" : {
        "commerce_id" : "13", 
        "stock_item_id" : "888", 
        "storehouse_id" : "2", 
        "stock_qty" : "1"
    }, 
    "Name" : "stockItem_1", 
    "reg_status" : "active"
}

then 

I want to get this result using query in browser like
?stock.commerce_id=13

so can you please help here for schema model and url query ?

Thank you...

### PR DESCRIPTION
**Pull request by electblake**
- Can query using fields like `/api/movies?actors.name=bob`
- Can query using $exists like `/api/movies?actors.0__exists=false`

Fixes https://github.com/baugarten/node-restful/issues/139

### CODE REVIEW

**Comment by electblake** [comment]
closing this as I think there is a bug during PUT requests

**Comment by resistcheat** [comment]
/api/products?populate=productId&productId.productParts=11 
Hi, is there any solution for select query of populated field (productId)

**Comment by urko-b** [comment]
¿Why this fix isn't in the last version of the npm? I have manually replace the piece of code for the contains function in model.js that was dowlnoaded when i run npm install:

Latest version: 
image

**Review by urko-b — APPROVED** [review]
These changes resolve the problem when filtering the properties of the array objects

**Comment by rochaneto2** [comment]
please accept this pull request !!

**Pull request closed without merging**
